### ISSUE TITLE
[Scheduled Maintenance] Site down for Maintenance

### ISSUE THREAD

**Issue by PengiCoder** [PengiOS/status#1]
**Additional context**
The status page is gonna be down as we try and fix it

**Comment by MrPiggy105** [comment]
which commit started it?

**Comment by PengiCoder** [comment]
The one where I updated the readme.md so I reverted it. Idk

**Comment by MrPiggy105** [comment]
"Scheduled maintenance"

I updated /.uptimerc.yml and it rebuilt the site... it works now. I'll do one more commit because I realised there was a mistake and then I'll close this.
